"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-18
"""

from alembic import op
import sqlalchemy as sa


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The app also creates tables on startup for frictionless local demos.
    # Production deployments should replace this placeholder with an autogenerated migration.
    pass


def downgrade() -> None:
    pass
